# Generated by Django 3.1.13 on 2021-11-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('valid', models.BooleanField()),
                ('ip', models.CharField(default='0', max_length=200)),
                ('type', models.CharField(default='BatPlug', max_length=200)),
                ('date', models.BigIntegerField(default=0)),
                ('values', models.JSONField()),
            ],
        ),
    ]
