# Generated by Django 3.1.13 on 2021-08-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_json', models.JSONField()),
                ('sensor', models.IntegerField(choices=[(1, 'BATDIMMER'), (2, 'BATMETER'), (3, 'BATMETERTRI'), (4, 'BATPLUG'), (5, 'BATSENSE'), (6, 'BATSTREETLIGHT')])),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
