# Generated by Django 3.1.13 on 2021-08-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edge_comp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payload',
            name='sensor',
        ),
    ]
