# Generated by Django 3.1.13 on 2021-08-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge_comp', '0002_remove_payload_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='payload',
            name='sensor',
            field=models.IntegerField(choices=[(1, 'BATDIMMER'), (2, 'BATMETER'), (3, 'BATMETERTRI'), (4, 'BATPLUG'), (5, 'BATSENSE'), (6, 'BATSTREETLIGHT')], default=1),
            preserve_default=False,
        ),
    ]
