# Generated by Django 3.1.13 on 2021-09-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge_comp', '0003_payload_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='sensor',
            field=models.IntegerField(blank=True, choices=[(1, 'BATDIMMER'), (2, 'BATMETER'), (3, 'BATMETERTRI'), (4, 'BATPLUG'), (5, 'BATSENSE'), (6, 'BATSTREETLIGHT')], null=True),
        ),
    ]
