# Generated by Django 3.1.13 on 2021-10-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge_comp', '0004_auto_20210906_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='payload',
            name='wrong',
            field=models.BooleanField(default=False),
        ),
    ]
