# Generated by Django 3.1.13 on 2021-10-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge_comp', '0005_payload_wrong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='wrong',
            field=models.BooleanField(),
        ),
    ]
