# Generated by Django 3.1.13 on 2021-10-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edge_comp', '0006_auto_20211011_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payload',
            old_name='wrong',
            new_name='valid',
        ),
    ]
